# -*- coding: utf-8 -*-
"""FINAL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OXKNeTcloPKslVrY9XfVWJTSh3Coum-z
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

# ==============================
# 1. LOAD IMAGES
# ==============================

img1 = cv2.imread('AgendaA.jpg')
img2 = cv2.imread('AgendaB.jpg')

if img1 is None or img2 is None:
    print("Error: Image not found.")
    exit()

# Convert to grayscale
gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

# ==============================
# 2. INITIALIZE SIFT
# ==============================

sift = cv2.SIFT_create()

# Detect keypoints and descriptors
kp1, des1 = sift.detectAndCompute(gray1, None)
kp2, des2 = sift.detectAndCompute(gray2, None)

print(f"Number of Keypoints in Image 1: {len(kp1)}")
print(f"Number of Keypoints in Image 2: {len(kp2)}")

# ==============================
# 3. VISUALIZE KEYPOINTS
# ==============================

img1_kp = cv2.drawKeypoints(img1, kp1, None,
                            flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

img2_kp = cv2.drawKeypoints(img2, kp2, None,
                            flags=cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS)

plt.figure(figsize=(15, 6))
plt.subplot(1, 2, 1)
plt.title("Keypoints Image 1")
plt.imshow(cv2.cvtColor(img1_kp, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.subplot(1, 2, 2)
plt.title("Keypoints Image 2")
plt.imshow(cv2.cvtColor(img2_kp, cv2.COLOR_BGR2RGB))
plt.axis('off')

plt.show()

# ==============================
# 4. FEATURE MATCHING
# ==============================

bf = cv2.BFMatcher(cv2.NORM_L2, crossCheck=False)

matches = bf.knnMatch(des1, des2, k=2)

# Lowe's Ratio Test
good_matches = []
for m, n in matches:
    if m.distance < 0.75 * n.distance:
        good_matches.append(m)

print(f"Total Matches: {len(matches)}")
print(f"Good Matches after Ratio Test: {len(good_matches)}")

# ==============================
# 5. DRAW MATCHES
# ==============================

matched_img = cv2.drawMatches(img1, kp1,
                               img2, kp2,
                               good_matches,
                               None,
                               flags=cv2.DrawMatchesFlags_NOT_DRAW_SINGLE_POINTS)

plt.figure(figsize=(15, 8))
plt.title("SIFT Feature Matching")
plt.imshow(cv2.cvtColor(matched_img, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.show()